### ISSUE TITLE
jupyter notebook icon not appearing

### ISSUE THREAD

**Issue by TfedUD** [pyxll/pyxll-notebook#1]
new to pyxll:     post pyxll-jupyter install:   my anti-virus blocked/quarentined some of the pyxll-jupyter related files ect:  renewed and unblocked the related items: and still no-joy with pyxll-jupyter
windows 10
excel 64bit
py 3.8

**Comment by TfedUD** [comment]
full uninstall reinstall of pyxll and pyxll-jupyter: no-joy

**Comment by tonyroberts** [comment]
This issue relates to the pyxll-jupyter project here https://github.com/pyxll/pyxll-jupyter, not this repo. However, this is being handled by PyXLL support and so I will close this issue now.
